const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_FILE || 'playwright');
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import fs from 'node:fs/promises';
const dir=process.env.TOY_WILDS_TEST_OUTPUT || join(tmpdir(),'toy-wilds-verification');await fs.mkdir(dir,{recursive:true});
const browser=await chromium.launch({headless:true,executablePath:process.env.PLAYWRIGHT_EXECUTABLE_PATH,args:['--use-gl=angle','--use-angle=swiftshader']});
const page=await browser.newPage({viewport:{width:1440,height:900}});const errors=[],checks=[];page.on('pageerror',e=>errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));const advance=ms=>page.evaluate(ms=>window.advanceTime(ms),ms);const check=(label,ok)=>{if(!ok)throw Error(label);checks.push(label)};
try{
await page.goto(process.env.TOY_WILDS_URL || 'http://127.0.0.1:4185');await page.waitForFunction(()=>window.render_game_to_text&&JSON.parse(window.render_game_to_text()).ready&&JSON.parse(window.render_game_to_text()).equipmentBag);await advance(1);check('welcome', (await state()).mode==='welcome');await page.locator('#start').click();await advance(50);
await page.locator('#bag').click();check('bag opens before collecting the sample', (await state()).mode==='inventory'&&!(await state()).pickup.collected);await page.keyboard.press('Escape');check('empty bag returns to world', (await state()).mode==='world');
await page.keyboard.press('f');await page.waitForFunction(()=>!!document.fullscreenElement);await page.keyboard.press('f');await page.waitForFunction(()=>!document.fullscreenElement);check('F toggles fullscreen',true);await page.screenshot({path:dir+'/world.png'});let s=await state();const start=s.player;
await page.keyboard.down('ArrowRight');await advance(350);await page.keyboard.up('ArrowRight');s=await state();check('camera relative keyboard movement',Math.hypot(s.player.x-start.x,s.player.z-start.z)>.8);
s=await state();await page.mouse.click(s.pickup.approachScreen.x,s.pickup.approachScreen.y);check('ground click computes a route',(await state()).pathLength>0);await advance(350);await page.locator('#pause').click();const beforePause=await state();await page.keyboard.down('ArrowUp');await advance(1500);await page.keyboard.up('ArrowUp');s=await state();check('pause freezes movement and local world motion',s.worldTime===beforePause.worldTime&&s.player.x===beforePause.player.x&&s.player.z===beforePause.player.z);await page.locator('#resume').click();
await page.locator('#marker').click();check('marker produces navigable route',(await state()).pathLength>0);await advance(6000);s=await state();check('walked near equipment',s.pickup.near&&!s.pickup.collected);await page.screenshot({path:dir+'/approach.png'});
await page.keyboard.press('e');await advance(500);s=await state();check('pickup opens inventory and records exactly one local item',s.mode==='inventory'&&s.inventory.length===1&&s.pickup.collected);check('no real award or profile write',s.awardWritten===false&&s.profileWritten===false);await page.screenshot({path:dir+'/equipment-bag.png'});await page.locator('#inventory-demo-card').click();await advance(500);check('picked sample opens its physical card from inventory',(await state()).mode==='card');await page.screenshot({path:dir+'/card-front.png'});
await page.mouse.move(820,410);await advance(400);s=await state();check('pointer tilt',Math.abs(s.card.rotation[0])+Math.abs(s.card.rotation[1])>.005);await page.mouse.move(25,875);await advance(1000);s=await state();check('leaving card settles',Math.abs(s.card.rotation[0])+Math.abs(s.card.rotation[1])<.002);
await page.mouse.click(720,450);await advance(800);check('click flips to back',(await state()).card.flipped);await page.screenshot({path:dir+'/card-back.png'});await page.keyboard.press('Enter');await advance(800);check('Enter flips to front',!(await state()).card.flipped);await page.keyboard.press('Space');await advance(800);check('Space flips to back',(await state()).card.flipped);
await page.keyboard.press('Escape');check('card Escape returns to inventory with item',(await state()).mode==='inventory'&&(await state()).inventory.length===1);await page.keyboard.press('Escape');check('inventory Escape returns to same world with item',(await state()).mode==='world'&&(await state()).inventory.length===1);await page.keyboard.press('e');check('pickup cannot duplicate item',(await state()).inventory.length===1);await page.locator('#bag').click();check('bag reopens inventory',(await state()).mode==='inventory');await page.locator('#inventory-demo-card').click();await page.locator('#return').click();check('card return button returns to inventory',(await state()).mode==='inventory');await page.keyboard.press('Escape');
await page.keyboard.down('ArrowDown');await advance(20000);await page.keyboard.up('ArrowDown');s=await state();check('walk cannot cross world bounds',s.player.x<=s.bounds.maxX&&s.player.z<=s.bounds.maxZ&&s.player.x>=s.bounds.minX&&s.player.z>=s.bounds.minZ);check('walk cannot enter obstacles',!s.obstacles.some(c=>c.r!==undefined?Math.hypot(s.player.x-c.x,s.player.z-c.z)<c.r+.23:Math.abs(s.player.x-c.x)<c.halfX+.23&&Math.abs(s.player.z-c.z)<c.halfZ+.23));
await page.locator('#pause').click();await page.locator('#restart').click();s=await state();check('restart resets only local exploration',s.mode==='world'&&!s.pickup.collected&&s.inventory.length===0&&s.player.x===0&&s.player.z===9);
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#marker').click();await advance(6000);await page.keyboard.press('e');await advance(500);await page.locator('#inventory-demo-card').click();await page.mouse.move(820,410);await advance(500);s=await state();check('reduced motion disables tilt',s.reducedMotion&&s.card.rotation[0]===0&&s.card.rotation[1]===0);await page.mouse.click(720,450);await advance(1);check('reduced motion preserves immediate flip',(await state()).card.rotation[1]===Math.PI);
await page.setViewportSize({width:390,height:844});await advance(50);check('mobile no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth===innerWidth));await page.screenshot({path:dir+'/mobile-card.png'});await page.locator('#return').click();await advance(50);await page.screenshot({path:dir+'/mobile-inventory.png'});await page.keyboard.press('Escape');await advance(50);await page.screenshot({path:dir+'/mobile-world.png'});
check('no browser errors',errors.length===0);await fs.writeFile(dir+'/report.json',JSON.stringify({checks,errors,final:await state()},null,2));console.log(JSON.stringify({passed:checks.length,checks,errors}));
}catch(error){await page.screenshot({path:dir+'/failure.png'});console.error(error);console.log(JSON.stringify({checks,errors,state:await state()}));process.exitCode=1}finally{await browser.close()}
