import * as THREE from 'three';
import {createRelic} from './actors.js';

export function createCard(){
 const group=new THREE.Group();group.name='holy-mirror-preview-card';
 const shape=new THREE.Shape(),w=4.15,h=6.3,r=.2,x=-w/2,y=-h/2;
 shape.moveTo(x+r,y);shape.lineTo(x+w-r,y);shape.quadraticCurveTo(x+w,y,x+w,y+r);shape.lineTo(x+w,y+h-r);shape.quadraticCurveTo(x+w,y+h,x+w-r,y+h);shape.lineTo(x+r,y+h);shape.quadraticCurveTo(x,y+h,x,y+h-r);shape.lineTo(x,y+r);shape.quadraticCurveTo(x,y,x+r,y);
 const geo=new THREE.ExtrudeGeometry(shape,{depth:.12,bevelEnabled:true,bevelSize:.035,bevelThickness:.035,bevelSegments:2,steps:1});
 const body=new THREE.Mesh(geo,new THREE.MeshStandardMaterial({color:0xc6a671,roughness:.58}));body.position.z=-.08;group.add(body);
 const uniforms={uView:{value:new THREE.Vector3(0,0,1)}};
 const surface=new THREE.Mesh(new THREE.PlaneGeometry(4.03,6.14),new THREE.ShaderMaterial({uniforms,vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}',fragmentShader:`varying vec2 vUv;uniform vec3 uView;void main(){vec2 p=vUv-.5;float phase=p.x*2.1+p.y*1.4+uView.x*4.+uView.y*3.;vec3 spectrum=.5+.5*cos(6.28318*(phase+vec3(0.,.33,.67)));float band=pow(max(0.,1.-abs(p.x+p.y*.6-uView.x*2.)),7.);vec3 base=mix(vec3(.065,.19,.19),vec3(.16,.30,.28),vUv.y);float rings=pow(max(0.,cos(length(p*vec2(1.,1.5))*43.)),14.)*.1;vec3 col=base+spectrum*(.05+band*.16)+rings*vec3(.25,.43,.37);gl_FragColor=vec4(col,1.);}`}));surface.position.z=.1;group.add(surface);
 const model=createRelic();model.scale.setScalar(1.25);model.position.set(0,.1,.52);group.add(model);
 function texture(back){const c=document.createElement('canvas');c.width=830;c.height=1260;const ctx=c.getContext('2d');if(back){ctx.fillStyle='#eae5d1';ctx.fillRect(0,0,830,1260)}ctx.strokeStyle=back?'#879b84':'#afbd95';ctx.lineWidth=2;ctx.strokeRect(37,37,756,1186);ctx.fillStyle=back?'#244a41':'#f6efd4';ctx.textAlign='left';ctx.font='22px sans-serif';ctx.fillText(back?'FIELD NOTES / 001':'TOY WILDS / 001',66,94);ctx.textAlign='right';ctx.fillText('圣 · SSR',764,94);ctx.textAlign='center';ctx.font='48px "Songti SC", serif';ctx.fillText('万象重构镜',415,172);
 if(back){ctx.strokeStyle='#4d7e70';ctx.lineWidth=14;[88,122,156].forEach((radius,i)=>{ctx.beginPath();ctx.arc(415,428,radius,.28+i*.12,5.4+i*.12);ctx.stroke()});ctx.fillStyle='#29a4ab';ctx.beginPath();ctx.arc(415,428,55,0,Math.PI*2);ctx.fill();ctx.fillStyle='#244a41';ctx.font='30px "Songti SC", serif';ctx.fillText('三环重连 · 一池成域',415,685);ctx.font='25px sans-serif';['器物的缺口，延伸为水路的开口。','桥接让分散的路径重新相遇。','水边的生灵，拥有自己的栖息地。'].forEach((t,i)=>ctx.fillText(t,415,774+i*57));ctx.font='21px sans-serif';ctx.fillStyle='#63776c';ctx.fillText('美术与交互样卡',415,1060);ctx.fillText('探索拾取不会颁发真实 Skill 成就',415,1102)}else{ctx.font='28px "Songti SC", serif';ctx.fillText('镜环重连，水路成域。',415,1081);ctx.font='19px sans-serif';ctx.fillStyle='#c1d3b9';ctx.fillText('一件装备 · 一个属于它的小世界',415,1130)}ctx.font='17px sans-serif';ctx.fillStyle=back?'#667b6c':'#9eb4a0';ctx.fillText('设计预览  /  永久成就与个人能力分别记录',415,1190);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;return tex}
 const frontPrint=new THREE.Mesh(new THREE.PlaneGeometry(4.03,6.14),new THREE.MeshBasicMaterial({map:texture(false),transparent:true,depthWrite:false}));frontPrint.position.z=.85;group.add(frontPrint);
 const back=new THREE.Mesh(new THREE.PlaneGeometry(4.03,6.14),new THREE.MeshBasicMaterial({map:texture(true)}));back.position.z=-.123;back.rotation.y=Math.PI;group.add(back);
 let targetX=0,targetY=0,flipped=false;
 return{group,body,hover(x,y,reduced){targetX=reduced?0:-y*.10;targetY=(flipped?Math.PI:0)+(reduced?0:x*.12)},settle(){targetX=0;targetY=flipped?Math.PI:0},flip(){flipped=!flipped;targetX=0;targetY=flipped?Math.PI:0},reset(){flipped=false;targetX=0;targetY=0;group.rotation.set(0,0,0)},update(dt,camera,reduced){const ease=reduced?1:1-Math.exp(-dt*13);group.rotation.x+=(targetX-group.rotation.x)*ease;group.rotation.y+=(targetY-group.rotation.y)*ease;group.updateMatrixWorld(true);uniforms.uView.value.copy(camera.position).applyMatrix4(new THREE.Matrix4().copy(group.matrixWorld).invert()).normalize()},get state(){return{flipped,rotation:[group.rotation.x,group.rotation.y],foilView:uniforms.uView.value.toArray()}}};
}
