import * as THREE from 'three';
import {createWorld} from './world.js';
import {createRelic,createExplorer} from './actors.js';
import {createNavigation} from './navigation.js';
import {createCard} from './card.js';
import {createInventory} from './inventory.js';
const $=id=>document.getElementById(id),canvas=$('game');
try{
 const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:false,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;
 const scene=new THREE.Scene();scene.background=new THREE.Color(0xeac194);scene.fog=new THREE.Fog(0xeac194,55,100);
 const world=createWorld();scene.add(world.group);
 const navigation=createNavigation(world);
 const ambient=new THREE.HemisphereLight(0xfff7e4,0x92927e,2.0);scene.add(ambient);
 const sun=new THREE.DirectionalLight(0xfff1df,3.0);sun.position.set(-12,22,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24,near:.5,far:65});sun.shadow.normalBias=.035;sun.shadow.bias=-.0001;scene.add(sun);
 const camera=new THREE.OrthographicCamera(-20,20,15,-15,.1,140);const focus=new THREE.Vector3(1,0,2);const cameraOffset=new THREE.Vector3(17,22,24);camera.position.copy(focus).add(cameraOffset);camera.lookAt(focus);
 const explorer=createExplorer();explorer.group.position.set(world.spawn.x,0,world.spawn.z);scene.add(explorer.group);
 const relic=createRelic();relic.scale.setScalar(.42);relic.position.set(world.pickup.x,1.3,world.pickup.z);relic.rotation.y=.45;scene.add(relic);
 const destination=new THREE.Mesh(new THREE.RingGeometry(.25,.33,28),new THREE.MeshBasicMaterial({color:0xfff1ca,side:THREE.DoubleSide,transparent:true,opacity:.85}));destination.rotation.x=-Math.PI/2;destination.position.y=.035;destination.visible=false;scene.add(destination);
 const cardScene=new THREE.Scene();cardScene.background=new THREE.Color(0xe6e6d9);cardScene.add(new THREE.HemisphereLight(0xffffff,0x708675,2.5));const cardLight=new THREE.DirectionalLight(0xffeacf,3.4);cardLight.position.set(-4,6,8);cardScene.add(cardLight);const cardFill=new THREE.DirectionalLight(0x82dee7,1.3);cardFill.position.set(4,1,5);cardScene.add(cardFill);
 const cardCamera=new THREE.PerspectiveCamera(38,1,.1,80);const card=createCard();cardScene.add(card.group);
 const media=matchMedia('(prefers-reduced-motion: reduce)');let reduced=media.matches;media.addEventListener('change',event=>{reduced=event.matches;card.settle()});
 let inventory=null;let cardReturn='world';
 const avatarScene=new THREE.Scene();avatarScene.background=new THREE.Color(0xd6d5bc);avatarScene.add(new THREE.HemisphereLight(0xfff9e8,0x748a78,2.8));const avatarLight=new THREE.DirectionalLight(0xffedd4,3.3);avatarLight.position.set(-2,5,4);avatarScene.add(avatarLight);const avatar=createExplorer();avatar.group.rotation.y=-.3;avatarScene.add(avatar.group);const avatarCamera=new THREE.PerspectiveCamera(32,1,.1,20);avatarCamera.position.set(1.7,1.15,3);avatarCamera.lookAt(0,.58,0);const platform=new THREE.Mesh(new THREE.CylinderGeometry(.8,.88,.13,12),new THREE.MeshStandardMaterial({color:0xb3bda1,roughness:1}));platform.position.y=-.07;avatarScene.add(platform);const heldRelic=createRelic();heldRelic.scale.setScalar(.21);heldRelic.position.set(.42,.62,.10);heldRelic.rotation.y=.12;avatarScene.add(heldRelic);
 const state={mode:'welcome',collected:false,path:[],time:0,walk:0,near:false,toast:0,steps:0};const keys=new Set();let last=performance.now(),manual=false,active=true;
 const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),ground=new THREE.Plane(new THREE.Vector3(0,1,0),0),hit=new THREE.Vector3();
 function resize(){renderer.setSize(innerWidth,innerHeight);const aspect=innerWidth/innerHeight;const height=aspect<.8?24:15.8;camera.left=-height*aspect/2;camera.right=height*aspect/2;camera.top=height/2;camera.bottom=-height/2;camera.updateProjectionMatrix();cardCamera.aspect=aspect;cardCamera.position.set(0,0,Math.max(11.3,5/(2*Math.tan(THREE.MathUtils.degToRad(19))*aspect)));cardCamera.lookAt(0,0,0);cardCamera.updateProjectionMatrix();render()}
 function notify(text){$('message').textContent=text;state.toast=3.5;$('message').classList.add('visible')}
 function setMode(mode){state.mode=mode;document.body.dataset.mode=mode;keys.clear();state.path=[];destination.visible=false;card.settle();$('welcome').hidden=mode!=='welcome';$('pause-panel').hidden=mode!=='paused';$('card-ui').hidden=mode!=='card';$('region').hidden=['card','inventory'].includes(mode);$('map-footer').hidden=['card','inventory'].includes(mode);$('marker').hidden=mode!=='world';$('travel').hidden=true;$('pause').hidden=mode==='welcome';canvas.setAttribute('aria-label',mode==='card'?'万象重构镜三维样卡，鼠标移入轻转，点击或 Enter、空格翻面，Esc 返回':'玩具旷野，点击小径移动，WASD 或方向键行走，接近镜体按 E 拾取');if(inventory){if(mode==='inventory')inventory.open(state.collected);else inventory.close()}if(mode==='world'||mode==='card')canvas.focus({preventScroll:true});render()}
 function reset(){state.collected=false;state.near=false;state.steps=0;state.walk=0;state.time=0;explorer.group.position.set(world.spawn.x,0,world.spawn.z);explorer.animateWalk(0,false);relic.visible=true;card.reset();$('bag').disabled=false;$('bag').setAttribute('aria-label','打开角色与装备袋');$('bag-label').textContent='角色与装备';$('quest').textContent='沿着暖色小径，找到池畔的镜。';setMode('world')}
 function openCard(origin='world'){if(!state.collected)return;cardReturn=origin;card.reset();setMode('card')}
 function openInventory(){setMode('inventory')}
 function pickup(){if(state.mode!=='world'||state.collected)return;if(!state.near){notify('再走近一些，就能拾取镜体。');return}state.collected=true;relic.visible=false;$('bag').disabled=false;$('bag').setAttribute('aria-label','打开角色与装备袋');$('bag-label').textContent='角色与装备 · 1';$('quest').textContent='镜已入袋。水路与守护者仍留在这里。';openInventory()}
 function route(target){if(state.mode!=='world')return;state.path=navigation.path(explorer.group.position,target);if(state.path.length){const p=state.path.at(-1);destination.position.set(p.x,.035,p.z);destination.visible=true;$('travel').hidden=false}else{notify('这边走不通，试试旁边的小径。')}}
 function approach(){if(state.collected){openCard();return}if(state.near)pickup();else route({x:world.pickup.x,z:world.pickup.z+1.65})}
 $('start').onclick=()=>setMode('world');$('resume').onclick=()=>setMode('world');$('restart').onclick=reset;$('bag').onclick=openInventory;$('return').onclick=()=>setMode(cardReturn);$('marker').onclick=approach;$('pause').onclick=()=>setMode(state.mode==='paused'?'world':'paused');
 function aim(event,cam){const r=canvas.getBoundingClientRect();pointer.set((event.clientX-r.left)/r.width*2-1,-(event.clientY-r.top)/r.height*2+1);raycaster.setFromCamera(pointer,cam)}
 function onCard(event){aim(event,cardCamera);return raycaster.intersectObject(card.body,false).length>0}
 canvas.addEventListener('pointermove',event=>{if(state.mode!=='card')return;if(event.pointerType!=='mouse'||!onCard(event)){card.settle();return}card.hover(pointer.x*2,-pointer.y,reduced);canvas.style.cursor='pointer'});
 canvas.addEventListener('pointerleave',()=>{card.settle();canvas.style.cursor='default'});
 canvas.addEventListener('click',event=>{if(state.mode==='card'){if(onCard(event)){card.flip();canvas.focus({preventScroll:true})}return}if(state.mode!=='world')return;aim(event,camera);const hits=raycaster.intersectObject(relic,true);if(relic.visible&&hits.length){approach();return}if(raycaster.ray.intersectPlane(ground,hit))route({x:hit.x,z:hit.z});canvas.focus({preventScroll:true})});
 document.addEventListener('keydown',event=>{const k=event.key.toLowerCase();if(document.querySelector('#inventory-detail[open]'))return;if(state.mode==='inventory'){if(k==='escape'){event.preventDefault();setMode('world')}return}if(event.target instanceof HTMLButtonElement&&['enter',' '].includes(k))return;if(k==='escape'){event.preventDefault();if(state.mode==='card')setMode(cardReturn);else if(state.mode==='paused')setMode('world');else if(state.mode==='world')setMode('paused');return}if(k==='f'&&!event.repeat){event.preventDefault();const promise=document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();promise?.catch(()=>notify('当前窗口暂不支持全屏。'));return}if(state.mode==='card'){if(['enter',' '].includes(k)&&!event.repeat){event.preventDefault();card.flip()}return}if(state.mode!=='world')return;if(k==='p'&&!event.repeat){setMode('paused');return}if(k==='e'&&!event.repeat){event.preventDefault();pickup();return}if(['w','a','s','d','arrowup','arrowleft','arrowdown','arrowright'].includes(k)){event.preventDefault();keys.add(k);state.path=[];destination.visible=false;$('travel').hidden=true}});
 document.addEventListener('keyup',event=>keys.delete(event.key.toLowerCase()));window.addEventListener('blur',()=>keys.clear());document.addEventListener('visibilitychange',()=>{active=!document.hidden;keys.clear();last=performance.now();if(!active)card.settle()});
 function step(dt){if(!active)return;if(state.toast>0){state.toast-=dt;if(state.toast<=0)$('message').classList.remove('visible')}if(state.mode==='card'){card.update(dt,cardCamera,reduced);return}if(state.mode!=='world')return;state.time+=dt;
  let dx=0,dz=0;const horizontal=Number(keys.has('d')||keys.has('arrowright'))-Number(keys.has('a')||keys.has('arrowleft')),vertical=Number(keys.has('s')||keys.has('arrowdown'))-Number(keys.has('w')||keys.has('arrowup'));
  if(horizontal||vertical){dx=horizontal*.816+vertical*.578;dz=-horizontal*.578+vertical*.816}else if(state.path.length){const p=state.path[0],pos=explorer.group.position;dx=p.x-pos.x;dz=p.z-pos.z;if(Math.hypot(dx,dz)<.075){state.path.shift();dx=0;dz=0}if(!state.path.length){destination.visible=false;$('travel').hidden=true}}
  const len=Math.hypot(dx,dz),pos=explorer.group.position,oldX=pos.x,oldZ=pos.z;if(len>.001){const travel=Math.min(3.3*dt,len);dx=dx/len*travel;dz=dz/len*travel;if(navigation.walkable(pos.x+dx,pos.z))pos.x+=dx;if(navigation.walkable(pos.x,pos.z+dz))pos.z+=dz;const moved=Math.hypot(pos.x-oldX,pos.z-oldZ);if(moved>0){state.steps+=moved;state.walk+=dt*9;explorer.group.rotation.y=Math.atan2(dx,dz)}else if(state.path.length){state.path=[];destination.visible=false;$('travel').hidden=true}}
  const moving=Math.hypot(pos.x-oldX,pos.z-oldZ)>.0001;explorer.animateWalk(state.walk,moving&&!reduced);state.near=Math.hypot(pos.x-world.pickup.x,pos.z-world.pickup.z)<2.3;world.update(state.time,{active:true,reducedMotion:reduced});
  const nextFocus=new THREE.Vector3(1+pos.x*.32,0,1+pos.z*.22);focus.lerp(nextFocus,1-Math.exp(-dt*3));camera.position.copy(focus).add(cameraOffset);camera.lookAt(focus);
 }
 function project(x,y,z,cam=camera){const p=new THREE.Vector3(x,y,z).project(cam);return{x:Math.round((p.x*.5+.5)*innerWidth),y:Math.round((-.5*p.y+.5)*innerHeight),visible:p.z<1&&p.x>-1&&p.x<1&&p.y>-1&&p.y<1}}
 function render(){renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);if(state.mode==='inventory'&&inventory){renderer.setClearColor(0xe9e6d5);renderer.clear();const r=inventory.viewport;heldRelic.visible=state.collected;if(r.width>0&&r.height>0&&r.bottom>0&&r.top<innerHeight){avatarCamera.aspect=r.width/r.height;avatarCamera.updateProjectionMatrix();renderer.setViewport(r.left,innerHeight-r.bottom,r.width,r.height);renderer.setScissor(Math.max(0,r.left),Math.max(0,innerHeight-r.bottom),Math.min(r.width,innerWidth-r.left),Math.max(0,Math.min(innerHeight,r.bottom)-Math.max(0,r.top)));renderer.setScissorTest(true);renderer.render(avatarScene,avatarCamera)}renderer.setScissorTest(false);renderer.setViewport(0,0,innerWidth,innerHeight);return}if(state.mode==='card'){renderer.render(cardScene,cardCamera);$('return').textContent=cardReturn==='inventory'?'← 返回装备袋':'← 返回旷野';$('card-help').textContent=(card.state.flipped?'点击卡片回到正面':'移入卡片轻转 · 点击卡片翻面')+' · Esc 返回'+(cardReturn==='inventory'?'装备袋':'旷野');return}renderer.render(scene,camera);const p=project(world.pickup.x,2.25,world.pickup.z);$('marker').hidden=state.mode!=='world'||!p.visible||state.collected;$('marker').style.left=p.x+'px';$('marker').style.top=p.y+'px';$('marker').classList.toggle('near',state.near);$('marker-label').textContent=state.near?'E 拾取 · 万象重构镜':'万象重构镜';$('distance').textContent=Math.round(Math.hypot(explorer.group.position.x-world.pickup.x,explorer.group.position.z-world.pickup.z))+' m';$('hint').textContent=state.near&&!state.collected?'E 拾取 / 点击镜体':'点击地面前往 / WASD 行走'}
 window.render_game_to_text=()=>JSON.stringify({ready:!!inventory,mode:state.mode,coordinateSystem:'Y up; X east, Z south; arrow controls camera-relative; units meters',player:{x:+explorer.group.position.x.toFixed(3),z:+explorer.group.position.z.toFixed(3)},pickup:{...world.pickup,near:state.near,collected:state.collected,screen:project(world.pickup.x,1.3,world.pickup.z),approachScreen:project(world.pickup.x,0,world.pickup.z+1.65)},inventory:state.collected?['wanxiang-mirror']:[],equipmentBag:inventory?.state||null,awardWritten:false,profileWritten:false,pathLength:state.path.length,bounds:world.bounds,obstacles:world.colliders,card:card.state,reducedMotion:reduced,worldTime:+state.time.toFixed(3),drawCalls:renderer.info.render.calls});
 window.advanceTime=ms=>{manual=true;const count=Math.max(1,Math.ceil(ms/(1000/60)));for(let i=0;i<count;i++)step(ms/1000/count);render()};
 function animate(now){const dt=Math.min((now-last)/1000,.05);last=now;if(!manual){step(dt);if(active)render()}requestAnimationFrame(animate)}
 inventory=await createInventory({onClose:()=>setMode('world'),onDemo:()=>openCard('inventory'),onChange:()=>{if(state.mode==='inventory')render()}});window.addEventListener('resize',resize);resize();setMode('welcome');requestAnimationFrame(animate);
}catch(error){console.error(error);$('fatal').hidden=false;$('fatal').textContent='旷野暂时无法加载：'+error.message;window.render_game_to_text=()=>JSON.stringify({ready:false,error:error.message})}
