const STORAGE='toy-wilds.role-loadouts.v1';
const uuid=/^[a-zA-Z0-9_-]{8,100}$/;
export async function createInventory({onClose,onDemo,onChange}){
 const response=await fetch('./inventory.html');if(!response.ok)throw new Error('装备袋界面尚未就绪');
 const template=document.createElement('template');template.innerHTML=await response.text();document.body.append(template.content);
 const $=id=>document.getElementById(id),panel=$('inventory-panel');let snapshot=null,loading=false,error=null,tab='library',limit=24,query='',restoreFocus=null;
 let saved={target:'codex',loadouts:{}};try{const raw=JSON.parse(localStorage.getItem(STORAGE));if(raw&&typeof raw.target==='string'&&raw.loadouts&&typeof raw.loadouts==='object'){saved={target:raw.target,loadouts:{}};for(const [key,ids]of Object.entries(raw.loadouts))if(/^[a-z0-9_-]+$/.test(key)&&Array.isArray(ids))saved.loadouts[key]=[...new Set(ids.filter(id=>typeof id==='string'&&uuid.test(id)))].slice(0,2000)}}catch{}
 let target=saved.target,demo=false;
 const selected=()=>saved.loadouts[target]||[];
 const text=(tag,cls,value)=>{const el=document.createElement(tag);el.className=cls;el.textContent=value;return el};
 function persist(){saved.target=target;try{localStorage.setItem(STORAGE,JSON.stringify(saved))}catch{error='浏览器未能保存清单；本次会话仍可继续准备。'}onChange?.()}
 function deployment(skill){const d=skill.deployments.find(d=>d.target===target);return d?.actualStatus==='current'?'current':d?'needs_check':'unregistered'}
 const labels={current:'已部署 · 与库一致',needs_check:'部署需检查',unregistered:'未登记部署'};
 function setList(){const entries=snapshot?.skills||[],ids=new Set(selected());const filtered=entries.filter(s=>(tab==='library'||ids.has(s.id))&&`${s.name} ${s.description}`.toLowerCase().includes(query));const grid=$('inventory-grid');grid.replaceChildren();
  for(const skill of filtered.slice(0,limit)){
   const state=deployment(skill),chosen=ids.has(skill.id),card=text('article','inventory-skill','');card.dataset.skillId=skill.id;card.dataset.state=state==='needs_check'?'needs_sync':state;card.dataset.carried=String(chosen);
   card.append(text('div','skill-emblem','◇'),text('h3','skill-name',skill.name),text('p','skill-description',skill.description||'暂无说明'),text('span','skill-state '+state,labels[state]),text('small','skill-version',skill.sourceRevision?`源版本 ${skill.sourceRevision.slice(0,10)} · 未评级`:'源版本未记录 · 未评级'));
   const actions=text('div','skill-actions',''),info=text('button','skill-info','信息');info.type='button';info.setAttribute('aria-label','查看 '+skill.name+' 的信息');info.onclick=()=>showDetail(skill);
   const toggle=text('button',chosen?'skill-remove':'skill-add',chosen?'移出清单':'加入清单');toggle.type='button';toggle.dataset.action=chosen?'remove':'add';toggle.setAttribute('aria-label',(chosen?'移出清单：':'加入清单：')+skill.name);toggle.setAttribute('aria-pressed',String(chosen));toggle.onclick=()=>{const next=new Set(selected());chosen?next.delete(skill.id):next.add(skill.id);saved.loadouts[target]=[...next];persist();render();const remaining=[...$('inventory-grid').querySelectorAll('[data-skill-id]')].find(el=>el.dataset.skillId===skill.id);(remaining?.querySelector('[data-action]')||$('inventory-tab-'+tab)).focus({preventScroll:true})};actions.append(info,toggle);card.append(actions);grid.append(card);
  }
  if(tab==='loadout')for(const id of selected().filter(id=>!entries.some(s=>s.id===id))){const card=text('article','inventory-skill missing','');card.append(text('h3','skill-name','条目待确认'),text('p','skill-description',`上次选择的 Skill ${id} 当前不在完整快照中。`));const remove=text('button','skill-remove','移出清单');remove.onclick=()=>{saved.loadouts[target]=selected().filter(x=>x!==id);persist();render()};card.append(remove);grid.append(card)}
  if(!grid.childElementCount&&!loading)grid.append(text('p','inventory-empty',query?'没有匹配的 Skill。':tab==='loadout'?'从仓库选择要带上的 Skill。':'暂无可用库数据，请重试读取。'));
  $('inventory-more').hidden=filtered.length<=limit;$('inventory-more').textContent=`继续查看（已显示 ${Math.min(limit,filtered.length)} / ${filtered.length}）`;
 }
 function render(){
  $('inventory-loading').hidden=!loading;$('inventory-error').hidden=!error&&!snapshot?.stale;$('inventory-error').textContent=error||snapshot?.error||'';$('inventory-refresh').disabled=loading;
  $('inventory-source-state').textContent=snapshot?`${snapshot.stale?'上次完整快照':'已核验'} · ${new Date(snapshot.observedAt).toLocaleTimeString('zh-CN',{hour12:false})}`:loading?'正在读取卡牌大师…':'尚未连接卡牌大师';
  $('inventory-library-count').textContent=snapshot?.total??'—';$('inventory-loadout-count').textContent=selected().length;
  $('inventory-tab-library').setAttribute('aria-selected',String(tab==='library'));$('inventory-tab-loadout').setAttribute('aria-selected',String(tab==='loadout'));
  $('inventory-tab-library').tabIndex=tab==='library'?0:-1;$('inventory-tab-loadout').tabIndex=tab==='loadout'?0:-1;$('inventory-grid').setAttribute('aria-labelledby','inventory-tab-'+tab);
  const targets=snapshot?.targets||[];const name=targets.find(t=>t.key===target)?.name||target;
  const current=snapshot?.skills.filter(s=>deployment(s)==='current')||[];const needs=snapshot?.skills.filter(s=>deployment(s)==='needs_check')||[];
  $('inventory-installed-count').textContent=snapshot?`${current.length} 已部署${needs.length?' · '+needs.length+' 需检查':''}`:'—';
  $('inventory-installed').replaceChildren(...current.map(s=>{const chip=text('button','installed-chip',s.name);chip.onclick=()=>{tab='library';query=s.name.toLowerCase();$('inventory-search').value=s.name;limit=24;render()};chip.title=`${name} 已部署，与库一致`;return chip}));
  if(!current.length)$('inventory-installed').append(text('span','inventory-empty',snapshot?'该目标没有已核验一致的受管部署。':'待读取部署记录。'));
  const m=snapshot?.multica;$('inventory-runtime-state').textContent=m?.installed?`Multica ${m.version} 已安装 · 待连接工作区`:'Multica 连接待核验';
  const demoBox=$('inventory-demo');demoBox.hidden=false;demoBox.replaceChildren();if(demo){const button=text('button','demo-chip','◇ 万象重构镜 · 探索样卡');button.id='inventory-demo-card';button.onclick=()=>onDemo();demoBox.append(button)}else demoBox.append(text('span','inventory-empty','池畔的探索样卡还未拾取。'));
  setList();
 }
 function showDetail(skill){let dialog=$('inventory-detail');if(!dialog){dialog=document.createElement('dialog');dialog.id='inventory-detail';dialog.className='inventory-detail';document.body.append(dialog)}dialog.replaceChildren(text('span','eyebrow','真实 Skill · 未评级'),text('h2','',skill.name),text('p','',skill.description||'暂无说明'),text('p','',labels[deployment(skill)]));const dl=document.createElement('dl');for(const [name,value]of[['Skill ID',skill.id],['来源类型',skill.sourceType],['源版本',skill.sourceRevision||'未记录'],['Manager 记录指纹',skill.recordedContentHash||'未记录']])dl.append(text('dt','',name),text('dd','',value));dialog.append(dl,text('p','inventory-detail-note','部署记录说明运行环境中的可用文件，不证明某个 Agent 已调用、掌握或实际加载。专属器物图尚未生成。'));const close=text('button','primary','返回装备袋');close.onclick=()=>dialog.close();dialog.append(close);dialog.showModal()}
 async function refresh(force=false){if(loading)return;loading=true;error=null;render();try{const r=await fetch('/api/inventory'+(force?'?refresh=1':''),{cache:'no-store'});const data=await r.json();if(!r.ok)throw new Error(data.error||'无法读取真实 Skill 库');if(!Array.isArray(data.skills)||data.skills.length!==data.total)throw new Error('数据不完整，未替换当前装备袋');snapshot=data;const available=data.targets.filter(t=>t.detected||data.skills.some(s=>s.deployments.some(d=>d.target===t.key)));if(!available.some(t=>t.key===target))target=available.some(t=>t.key==='codex')?'codex':available[0]?.key||'';$('inventory-target').replaceChildren(...available.map(t=>{const option=document.createElement('option');option.value=t.key;option.textContent=t.name+(t.detected?'':' · 目录未检测到');return option}));$('inventory-target').value=target;$('inventory-target').disabled=false;persist()}catch(e){error=snapshot?'实时读取失败，继续显示上次快照。':e.message;if(snapshot)snapshot={...snapshot,stale:true}}finally{loading=false;render();onChange?.()}}
 $('inventory-close').onclick=()=>onClose();$('inventory-refresh').onclick=()=>refresh(true);$('inventory-target').onchange=event=>{target=event.target.value;limit=24;persist();render()};$('inventory-search').oninput=event=>{query=event.target.value.toLowerCase();limit=24;setList()};$('inventory-tab-library').onclick=()=>{tab='library';limit=24;render()};$('inventory-tab-loadout').onclick=()=>{tab='loadout';limit=24;render()};$('inventory-more').onclick=()=>{limit+=24;setList()};
 for(const id of ['inventory-tab-library','inventory-tab-loadout'])$(id).addEventListener('keydown',event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();tab=event.key==='Home'?'library':event.key==='End'?'loadout':tab==='library'?'loadout':'library';limit=24;render();$('inventory-tab-'+tab).focus()}});
 panel.addEventListener('keydown',event=>{if(event.key==='Escape'){event.preventDefault();event.stopPropagation();onClose();return}if(event.key==='Tab'){const focusable=[...panel.querySelectorAll('button:not([disabled]):not([tabindex="-1"]),select:not([disabled]),input,[tabindex="0"]')].filter(el=>el.getClientRects().length);const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});
 return{open(collected){restoreFocus=document.activeElement;demo=collected;panel.hidden=false;render();$('inventory-close').focus();if(!snapshot||Date.now()-Date.parse(snapshot.observedAt)>30000)refresh()},close(){if(!panel.hidden){panel.hidden=true;restoreFocus?.focus?.({preventScroll:true})}},refresh,get viewport(){return $('inventory-character').getBoundingClientRect()},get state(){return{ready:!!snapshot,loading,stale:!!snapshot?.stale,total:snapshot?.total||0,runtimeTarget:target,roleRef:'local:explorer',draftSkillIds:[...selected()],actualDeployed:snapshot?.skills.filter(s=>deployment(s)==='current').length||0,multicaBound:false,error:error||null}}};
}
